Add handling for yield path & Added debug function for scan_context
project-tsurugi/jogasaki pull request #109
Opened 2024-08-06 08:05 UTC by YoshiakiNishimura

## Add handling for yield path 

 Enable rescheduling for the yield case

## Added debug function for scan_context

`std::cerr << ctx << std::endl`

```
context_base:
  task_context:         0x7f4ba0002060
  input_variables:      0x7f4ba0002a20
    variable_table:
      info:             0x7f4b2c005b80
      store:            0x7f4ba0002b80
      store value:      meta: int4*[4, 0]  data: 00-00-00-00-00-00-00-00
  output_variables:     0x7f4ba0002a20
    variable_table:
      info:             0x7f4b2c005b80
      store:            0x7f4ba0002b80
      store value:      meta: int4*[4, 0]  data: 00-00-00-00-00-00-00-00
  resource:             0x7f4ba0002580
  varlen_resource:      0x7f4ba0002480
  state:                0
  scan_context:
    stg:                0x7f4ba0002c60
    secondary_stg:      0x0
    transaction_context:0x7f4ba00011d0
    iterator:           0x7f4ba0002e20
    scan_info:          0x7f4ba0001720
    key_begin_size:     0
    key_end_size:       0
```

2024-08-06 08:37 UTC, kuron99 commented on src/jogasaki/executor/process/impl/ops/context_base.cpp
> +std::ostream& operator<<(std::ostream& os, const context_base& ctx) {
`std::left` や `std::hex` などのmanipulatorは一回設定すればよく、関数の先頭で `os` に対してセットすればいいのではないでしょうか。

`std::setw` だけが例外で、これは毎回呼び出す必要があるようです。
https://stackoverflow.com/a/1533222/1352863

2024-08-06 08:38 UTC, kuron99 commented on src/jogasaki/executor/process/impl/ops/context_base.cpp
> +    os << "context_base:\n";
`¥n`ではなく `std::endl` がいいと思います

2024-08-06 08:43 UTC, kuron99 commented on src/jogasaki/executor/process/impl/ops/context_base.h
> +    friend std::ostream& operator<<(std::ostream& os, const context_base& ctx);
jogasakiでは constは `&` や `*`の直前につける(constは後ろから前を修飾する)という方式で統一しているので、 `const context_base& ctx` は `context_base const& ctx` でお願いします。

2024-08-06 08:47 UTC, kuron99 commented on src/jogasaki/executor/process/impl/variable_table.h
> +    void debug_print(std::ostream& os, const std::string& indent = "") const;
`const std::string&` -> `std::string_view` が軽量でいいと思います

2024-08-06 09:07 UTC, YoshiakiNishimura commented on src/jogasaki/executor/process/impl/variable_table.h
> +    void debug_print(std::ostream& os, const std::string& indent = "") const;
修正して[eae6950](https://github.com/project-tsurugi/jogasaki/pull/109/commits/eae695091f5eb61eb0a816edf84732d56c605961)にcommitしました。

2024-08-06 09:19 UTC, YoshiakiNishimura commented on src/jogasaki/executor/process/impl/ops/context_base.cpp
> +    os << "context_base:\n";
フラッシュする必要性がないので\nにしましたが、jogasakiの改行はすべてstd::endlにしますか？

2024-08-06 09:23 UTC, kuron99 commented on src/jogasaki/executor/process/impl/ops/context_base.cpp
> +    os << "context_base:\n";
ああ、そういう使いわけであれば `\n` でもOKです。

2024-08-06 09:33 UTC, kuron99 commented on src/jogasaki/executor/process/impl/ops/context_base.cpp
> +    os << "context_base:\n";
ただ、その前にそもそも `operator<<` で改行やインデント等の整形をすべきか検討すべきですね。`operator<<` を使用した結果はサーバーログに書き出される事があり、サーバーログはgrep等で処理されるので、1行に情報がまとまっていることが求められます。

2024-08-06 09:44 UTC, kuron99 commented on src/jogasaki/executor/process/impl/ops/context_base.cpp
> +    os << "context_base:\n";
そういう点では見やすさよりもその要求を優先して改行・インデント等を行わない方が好ましいです。
またはpretty_printみたいな名前の関数を追加して、見やすさを優先した出力を行うという手もありますが、呼び出し側がどちらを使うか選ばないとならないのがいまいちですね。

2024-08-06 09:51 UTC, kuron99 commented on src/jogasaki/executor/process/impl/ops/context_base.cpp
> +       << static_cast<int>(ctx.state_) << "\n";
intだとコードを見ないと意味がわからないので、context_stateに文字列化するための `to_string_view` や `operator<<` を追加してそれを使ってもらえますか。

下記はfield_type_kindについて同様のことを行っているものですが、enum に関しては常に同様の関数があるべきと思います。
https://github.com/project-tsurugi/jogasaki/blob/master/include/jogasaki/api/field_type_kind.h#L60-L102

2024-08-06 10:00 UTC, kuron99 commented on src/jogasaki/executor/process/impl/variable_table.cpp
> +void variable_table::debug_print(std::ostream& os, std::string const& indent) const {
`operator<<` を使わずに新しく関数を作成しているのは理由がありますか？
`operator<<` に書きたい情報を追加してもらったほうが使い勝手がよさそうです。

2024-08-06 10:09 UTC, kuron99 requested changes
一旦レビュー完了でお返しします。

リッチなデータ構造のフォーマッティングに関しては、jsonで出力して外部ツールで読むときにキレイにするという方向もありだと思います。jogasakiの他の箇所でも複雑なデータをログに書いたりする際はそれをやっているところがあります。nlohmann::jsonあたりでjogasakiのコードを検索してみてください。

2024-08-07 02:09 UTC, YoshiakiNishimura commented on src/jogasaki/executor/process/impl/ops/context_base.cpp
> +    os << "context_base:\n";
提案ですが、LLVMと揃えませんか？
https://github.com/llvm/llvm-project/blob/main/llvm/include/llvm/IR/Value.h#L231
すなわち

- GDB用のdump関数
- Implement operator<<用のprint関数を用意する

ただ本格実装は
https://github.com/llvm/llvm-project/blob/main/llvm/lib/IR/AsmWriter.cpp#L5034
のように[raw_ostream](https://github.com/llvm/llvm-project/blob/main/llvm/lib/Support/raw_ostream.cpp)をゴリゴリに実装しないと無理なので今回私が作った関数は全部dump関数に移行して

ctx->dump()

で単に標準エラー出力をするようにしたいのですがいかがでしょうか？(データ整形は私の今のやり方(なんちゃってyamlで)

サーバログに関しては本件と切り離したいので今回はなしでいいですか？

2024-08-07 02:44 UTC, kuron99 commented on src/jogasaki/executor/process/impl/ops/context_base.cpp
> +    os << "context_base:\n";
GDBでの出力用と `operator<<` は分けるということですね。それならば前者についてはサーバーログと切り離して自由に作ってもらっていいと思います。
有り得そうなのは、dump関数の出来がよくてそれを結局サーバーログにも載せて使いたい、という事になる可能性ですが、まあそうなったらまたそのときまた考えましょう。

2024-08-07 04:32 UTC, YoshiakiNishimura commented
指摘反映しました

2024-08-07 04:34 UTC, YoshiakiNishimura commented
指摘反映しました

2024-08-07 04:54 UTC, kuron99 approved these changes
LGTM

2024-08-07 05:02 UTC, merged