Move key_begin and key_end members from scan_context to scan_info
project-tsurugi/jogasaki pull request #127
Opened 2024-10-22 09:31 UTC by YoshiakiNishimura

2024-10-22 10:01 UTC, YoshiakiNishimura commented
@kuron99 

scan_testまで貫通いたしましたのでレビューお願いいたします

2024-10-23 06:45 UTC, kuron99 commented on src/jogasaki/data/aligned_buffer.h
> +    void dump(std::ostream& out, int indent = 0) const noexcept;
doc commentを追加してください。あと、friend関数の上に移動させてください。

2024-10-23 06:50 UTC, kuron99 commented on src/jogasaki/executor/process/impl/processor.cpp
> +    request_context* resource
`resource` という名前も変更してください。

2024-10-23 07:15 UTC, kuron99 commented on test/jogasaki/operator_test_utils.h
> +    request_context request_context_{}; //NOLINT
これって必要なのでしょうか？どこかで使っています？

2024-10-23 07:25 UTC, kuron99 commented on src/jogasaki/executor/process/impl/task_context.cpp
> +std::shared_ptr<impl::scan_info> task_context::non_const_impl_scan_info() {
関数名が少し仰々しいので shared_scan_info あたりでどうでしょうか。
返り値の型も `std::shared_ptr<impl::scan_info> const&` にしてもらえますか。(コピーが不要な場合のために)

2024-10-23 07:25 UTC, YoshiakiNishimura commented on test/jogasaki/operator_test_utils.h
> +    request_context request_context_{}; //NOLINT
必要です
改造でscan::openでiterator関連の設定をしなくなった関係でscan_test.cppを通すためにscan_info::encode_key関数呼び出しが必要になりました。その関数の引数としてrequest_context_が必要です。
その代わり従来のmemory::lifo_paged_memory_resource resource_;  //NOLINTが不要になっていましたがこちらは消し忘れなのでresource_は消します

2024-10-23 07:28 UTC, kuron99 commented on src/jogasaki/executor/process/impl/ops/operator_builder.cpp
>      scan_info_ = create_scan_info(node, secondary_or_primary_index);
create_scan_infoにrequest_context_を渡してエンコードまでしてしまうほうがシンプルではないでしょうか

2024-10-23 07:35 UTC, kuron99 commented on test/jogasaki/operator_test_utils.h
> +    request_context request_context_{}; //NOLINT
了解。使っているのであればOKです。

2024-10-23 07:36 UTC, kuron99 requested changes
ざっくりとですが、レビューしてコメントしました。

2024-10-24 09:52 UTC, YoshiakiNishimura commented
@kuron99  対応しました

2024-10-25 08:13 UTC, kuron99 commented on src/jogasaki/executor/process/impl/ops/operator_builder.h
> +        request_context* request_context = nullptr
doc commentの `@param`部分も一緒に修正お願いします。

2024-10-25 08:23 UTC, kuron99 commented on src/jogasaki/executor/process/impl/ops/operator_builder.cpp
> +    std::unique_ptr<ops::context_base::memory_resource> varlen_resource,
ここはrequest_contextのrequest_resource()で取れるものを使うというのではダメですか？requestをconstructするのに必要なmemory resourceはあまり大きくないはずなので、この目的のためにglobal poolからアサインするのはもったいない印象です。

2024-10-25 08:54 UTC, YoshiakiNishimura commented on src/jogasaki/executor/process/impl/ops/operator_builder.cpp
> +    std::unique_ptr<ops::context_base::memory_resource> varlen_resource,
@kuron99 

scan_infoでbegin_key,end_keyを設定するためにjogasaki::executor::process::impl::ops::details::[encode_key](https://github.com/project-tsurugi/jogasaki/blob/master/src/jogasaki/executor/process/impl/ops/details/encode_key.cpp#L41C8-L41C18)を呼び出していますがこれの第一引数が request_context* contextなのでencode_keyを改造する必要があります。改造しますか？

```CPP
            expr::evaluator_context ctx{
                std::addressof(resource),
                context ? utils::make_function_context(*context->transaction()) : nullptr,
            };
```

global poolにアサインしているのはこれまでの挙動を変えたくないからで[ flow::create_task_context](https://github.com/project-tsurugi/jogasaki/blob/master/src/jogasaki/executor/process/flow.cpp#L164C36-L164C62)下記コードに引っ張らています。

```CPP
    ctx->work_context(
        std::make_unique<impl::work_context>(
            context_,
            operators.size(),
            info_->vars_info_list().size(),
            std::make_unique<memory::lifo_paged_memory_resource>(&global::page_pool()),
            std::make_unique<memory::lifo_paged_memory_resource>(&global::page_pool()),
            context_->database(),
            context_->transaction(),
            empty_input_from_shuffle_
        )
    );
```

今回ここは下記の通り、これまでと同じ状態を保つために少し面倒な改造を行っています。global::page_pool()からアサインしているのはオブジェクトの生存期間の問題ですか？

```CPP
    auto scan = ctx->shared_scan_info();
    ctx->work_context(
        std::make_unique<impl::work_context>(
            context_,
            operators.size(),
            info_->vars_info_list().size(),
            std::make_unique<memory::lifo_paged_memory_resource>(&global::page_pool()),
            (scan == nullptr)?std::make_unique<memory::lifo_paged_memory_resource>(&global::page_pool()):scan->varlen_resource(),
            context_->database(),
            context_->transaction(),
            empty_input_from_shuffle_
        )
    );
```

2024-10-25 09:29 UTC, kuron99 commented on src/jogasaki/executor/process/impl/scan_info.h
> +        std::vector<ops::details::search_key_field_info> const& begin_columns = {},
このPRでなくてもいいのですが、下記のような形でstd::string_view経由でキーを渡すコンストラクタが必要になりそうなので追加しておいてもいいかもしれません。(スキャンするキー区間を外部で作成した際にscan_infoを作る用途)
std::vector<ops::details::search_key_field_info>を受け取るコンストラクタはstd::string_view経由のコンストラクタに委譲できるとキレイですが、コンストラクタ内部で複数の変数にアクセスしたりすると難しいかもしれません。その場合は別々のコンストラクタでもいいと思います。
```
    explicit scan_info(
        std::string_view key_begin = {},
        kvs::end_point_kind begin_endpoint = kvs::end_point_kind::unbound,
        std::string_view key_end = {},
        kvs::end_point_kind end_endpoint = kvs::end_point_kind::unbound,
        std::unique_ptr<memory_resource> varlen_resource = nullptr,
        request_context* request_context = nullptr
    );
```

2024-10-25 09:45 UTC, kuron99 commented on src/jogasaki/executor/process/impl/ops/operator_builder.cpp
> +    std::unique_ptr<ops::context_base::memory_resource> varlen_resource,
> scan_infoでbegin_key,end_keyを設定するためにjogasaki::executor::process::impl::ops::details::[encode_key](https://github.com/project-tsurugi/jogasaki/blob/master/src/jogasaki/executor/process/impl/ops/details/encode_key.cpp#L41C8-L41C18)を呼び出していますがこれの第一引数が request_context* contextなのでencode_keyを改造する必要があります。改造しますか？

request_contextがGODオブジェクト化していてよくないのですが、いまのところ必要な場所にrequest_contextを渡すのはしょうがないかなと思っています。なので、request_contextをoperator_builder等にわたす点については問題ありません。

2024-10-25 09:55 UTC, kuron99 commented on src/jogasaki/executor/process/impl/ops/operator_builder.cpp
> +    std::unique_ptr<ops::context_base::memory_resource> varlen_resource,
> global poolにアサインしているのはこれまでの挙動を変えたくないからで[ flow::create_task_context](https://github.com/project-tsurugi/jogasaki/blob/master/src/jogasaki/executor/process/flow.cpp#L164C36-L164C62)下記コードに引っ張らています。

うーん、なるほど、work_contextへmake_uniqueして渡しているのがタイミングが変わったので移動してきた感じですか。ただ一旦scan_infoへ渡して、引き剥がしてimpl::work_contextへ渡すのが迂遠な感じはありますね。

2024-10-28 01:42 UTC, kuron99 commented on src/jogasaki/executor/process/impl/ops/operator_builder.cpp
> +    std::unique_ptr<ops::context_base::memory_resource> varlen_resource,
@YoshiakiNishimura work_contextのmemory resourceを使う必要はないと思うので、scan_infoを作成するのに使う必要がある場合は request_contextのrequest_resource() を使う、という方針にしましょう。

既存のコードはwork_contextが持つvarlen resourceを使っていました。これはprocess内のオペレータが並列化された際、その並列化単位の1個1個にアサインされたvarlen resourceで、並列で動く(可能性のある) scanの内部でエンコードを行うのでこれを使うしかありませんでした。
一方これからはscanの外部で並列化前にシングルスレッドで処理される部分(create_tasksやcreate_scan_info, operator_builderなど)でscan_infoを作ることになるので、ここではwork_contextのものを使う必要はなく、リクエスト全体で持っている(request_context::request_resource()で取得できる)ものをつかっていいと思います。

2024-10-28 02:09 UTC, kuron99 commented on src/jogasaki/executor/process/impl/scan_info.h
> +        std::vector<ops::details::search_key_field_info> const& begin_columns = {},
上記について、もう少し細かく考えました。

「scan_infoは純粋にスキャン区間をあらわすものとする」
「スキャン区間をstd::vector<search_key_field_info>で表していたのはやめ、(data::aligned_bufferを使って保存される) std::string_viewで表す」

というポリシーとし、scan外部でscan_infoを作成しやすくするべきと考えます。既存のコードはindexの構造に密になっていたのでsearch_key_field_infoでよかったのですが、今後は外部でキー分布等の情報だけからscan_infoを作ることになるのでなるべく余計な依存を持たず、純粋に区間を表すキーだけを保持するのがいいと思います。

そのため、エンコードしてキーを作る、という部分はscan_infoから分離してcreate_scan_info等に移動しましょう。そうすれば、コンストラクタはvarlen_resourceやrequest_contextを受け取らなくてよくなります。

エンコード中にエラーが起きた際にstatus_result_に詰めてscan実行時にチェックするというロジックもやめて、エンコードした部分からエラーを戻すようにしましょう。
processorのコンストラクタやoperator_builder内部で構造を構築している際にエラーが起きたときのエラー処理としてはimpl::compiler_exceptionを投げる、というやり方が可能です。下記のコードを参考にしてください。
https://github.com/project-tsurugi/jogasaki/blob/1d1e82800503627cb891317d1bec99db21fa9815/src/jogasaki/executor/process/impl/ops/write_existing.cpp#L411-L412

2024-10-28 02:12 UTC, kuron99 commented on src/jogasaki/executor/process/impl/ops/operator_builder.cpp
>      return std::make_shared<impl::scan_info>(
別のコメントでも述べましたが、この位置にエンコード処理を持ってくることを検討してもらえませんか。エンコードで使うためにここまではrequest_contextが必要ですが、scan_infoのコンストラクタにはrequest_context, varlen_resourceを渡さなくてすむと思っています。

2024-10-28 02:13 UTC, kuron99 requested changes
コメントしました。レビュー完了で一旦戻します。

2024-10-28 02:41 UTC, YoshiakiNishimura commented on src/jogasaki/executor/process/impl/ops/operator_builder.cpp
>      return std::make_shared<impl::scan_info>(
@kuron99 
これは最初のようにscan_info->encode_key(request_context)という感じでエンコード処理を分離するという認識であってます？

2024-10-28 02:49 UTC, kuron99 commented on src/jogasaki/executor/process/impl/ops/operator_builder.cpp
>      return std::make_shared<impl::scan_info>(
いえ、scan_infoからもエンコード処理を分離することを意図しています。scan_infoの外側でエンコードを行い、scan_infoは出来上がったものを受け取るだけにする。

2024-11-13 22:56 UTC, closed without merging